### ISSUE TITLE
API can't be in a subfolder.

### ISSUE THREAD

**Issue by Beanow** [webistor/webistor-app#15]
For example in the webistor app's `config.coffee`

```
module.exports =
  api:
    domain: 'localhost/webistor-api'
    port: 80
```

Results in requests like: `http://localhost/webistor-api:80/invitations/request`

Not sure if this was a wontfix known-issue, since you can define alternative localhost references.
